"""
centre_finder.py — Two-pass azimuthal variance minimisation for FPI ring centre.

Inputs: cal_image_L1.1.npy (or equivalent) generated by running load_real_image.py
Outputs-1: cal_image_step2_centre.png
Output-2: cal_image_centre.npz (the new seed used by annular_reduction.py)

Stage 1 — coarse grid search over ±var_search_px.
Stage 2 — Nelder-Mead from the best grid point.

Centre uncertainty is estimated from cost-surface curvature (finite-difference
second derivative at the minimum).

Usage
-----
    python ingest/centre_finder.py
"""

from __future__ import annotations

import os
import pathlib
import tkinter as tk
from dataclasses import dataclass
from tkinter import filedialog
from typing import Callable, Optional

import matplotlib.pyplot as plt
import numpy as np
from scipy.optimize import minimize


# ---------------------------------------------------------------------------
# Result dataclass
# ---------------------------------------------------------------------------

@dataclass
class CentreResult:
    """Output of the two-pass azimuthal variance centre finder."""
    # Pass 2 — Nelder-Mead refined result (authoritative)
    cx:           float   # fringe centre x, pixels
    cy:           float   # fringe centre y, pixels
    sigma_cx:     float   # 1σ uncertainty on cx, pixels
    sigma_cy:     float   # 1σ uncertainty on cy, pixels
    two_sigma_cx: float   # 2 × sigma_cx
    two_sigma_cy: float   # 2 × sigma_cy
    cost_at_min:  float   # variance cost at the Nelder-Mead minimum
    # Pass 1 — coarse grid search result (seed for pass 2)
    grid_cx:      float   # best-grid cx, pixels
    grid_cy:      float   # best-grid cy, pixels
    grid_cost:    float   # variance cost at the grid minimum


# ---------------------------------------------------------------------------
# Azimuthal variance cost function
# ---------------------------------------------------------------------------

def _variance_cost(
    cx: float,
    cy: float,
    image: np.ndarray,
    r_min_sq: float,
    r_max_sq: float,
    n_var_bins: int,
) -> float:
    """
    Sum of per-bin intensity variance over the annular region.

    Minimum at the true optical axis.  Uses biased variance per bin and
    np.bincount for vectorised computation (no Python loop over bins).
    """
    H, W = image.shape
    row_c, col_c = np.mgrid[0:H, 0:W]
    r2 = (row_c.astype(np.float64) - cy)**2 + (col_c.astype(np.float64) - cx)**2

    mask = (r2 >= r_min_sq) & (r2 < r_max_sq)
    r2_valid  = r2[mask]
    adu_valid = image[mask].astype(np.float64)

    if r2_valid.size < n_var_bins:
        return 1e30

    dr2 = r_max_sq / n_var_bins
    bin_idx = np.floor(r2_valid / dr2).astype(np.int32)
    bin_idx = np.clip(bin_idx, 0, n_var_bins - 1)

    counts = np.bincount(bin_idx, minlength=n_var_bins).astype(np.float64)
    sum_a  = np.bincount(bin_idx, weights=adu_valid,    minlength=n_var_bins)
    sum_a2 = np.bincount(bin_idx, weights=adu_valid**2, minlength=n_var_bins)

    good    = counts >= 2
    mean_sq = np.where(good, sum_a2 / np.where(good, counts, 1.0), 0.0)
    sq_mean = np.where(good, (sum_a / np.where(good, counts, 1.0))**2, 0.0)
    var_bins = np.where(good, mean_sq - sq_mean, 0.0)
    return float(np.sum(var_bins))


# ---------------------------------------------------------------------------
# Two-pass azimuthal variance minimisation
# ---------------------------------------------------------------------------

def azimuthal_variance_centre(
    image: np.ndarray,
    cx_seed: float,
    cy_seed: float,
    var_r_min_px: float = 5.0,
    var_r_max_px: Optional[float] = None,
    var_n_bins: int = 250,
    var_search_px: float = 15.0,
) -> tuple[float, float, float]:
    """
    Two-pass azimuthal variance minimisation.

    Pass 1 — coarse grid search over ±var_search_px with step
             max(2.0, var_search_px / 8) px.
    Pass 2 — Nelder-Mead from best grid point with small initial simplex.

    Returns (cx_fine, cy_fine, cost_min, grid_cx, grid_cy, grid_cost).

    Notes
    -----
    Single-pass Nelder-Mead fails on this cost function (narrow basin ~1 px
    wide); the two-pass approach is mandatory per spec Section 6.2.
    """
    H, W = image.shape
    if var_r_max_px is None:
        var_r_max_px = min(H, W) // 2 - 10

    r_min_sq = var_r_min_px ** 2
    r_max_sq = var_r_max_px ** 2

    def cost(xy):
        return _variance_cost(xy[0], xy[1], image, r_min_sq, r_max_sq, var_n_bins)

    # --- Pass 1: coarse grid search ---
    grid_step = max(2.0, var_search_px / 8.0)
    offsets   = np.arange(-var_search_px, var_search_px + grid_step * 0.5, grid_step)

    best_cost = np.inf
    best_cx   = cx_seed
    best_cy   = cy_seed

    for dy in offsets:
        for dx in offsets:
            c = cost([cx_seed + dx, cy_seed + dy])
            if c < best_cost:
                best_cost = c
                best_cx   = cx_seed + dx
                best_cy   = cy_seed + dy

    # --- Pass 2: Nelder-Mead from best grid point ---
    simplex_r = grid_step + 0.5
    x0 = np.array([best_cx, best_cy])
    initial_simplex = np.array([
        x0,
        x0 + [simplex_r, 0.0],
        x0 + [0.0, simplex_r],
    ])

    result = minimize(
        cost, x0,
        method="Nelder-Mead",
        options={
            "initial_simplex": initial_simplex,
            "xatol": 0.02,
            "fatol": 1.0,
            "maxiter": 500,
        },
    )

    cx_fine  = float(result.x[0])
    cy_fine  = float(result.x[1])
    cost_min = float(result.fun)
    return cx_fine, cy_fine, cost_min, best_cx, best_cy, best_cost


# ---------------------------------------------------------------------------
# Centre uncertainty from cost-surface curvature
# ---------------------------------------------------------------------------

def estimate_centre_uncertainty(
    cx: float,
    cy: float,
    cost_fn: Callable,
    delta_px: float = 0.5,
) -> tuple[float, float]:
    """
    Estimate 1σ uncertainty on cx and cy from curvature of cost surface.

    σ_cx = sqrt(2 / (d²C/dcx²))  at the minimum.
    Finite-difference second derivative with step delta_px.
    Clamped to [0.02, 5.0] px.
    """
    c0  = cost_fn([cx, cy])
    cxp = cost_fn([cx + delta_px, cy])
    cxm = cost_fn([cx - delta_px, cy])
    cyp = cost_fn([cx, cy + delta_px])
    cym = cost_fn([cx, cy - delta_px])

    d2cx = (cxp - 2.0 * c0 + cxm) / (delta_px ** 2)
    d2cy = (cyp - 2.0 * c0 + cym) / (delta_px ** 2)

    sigma_cx = float(np.sqrt(2.0 / d2cx)) if d2cx > 0 else 5.0
    sigma_cy = float(np.sqrt(2.0 / d2cy)) if d2cy > 0 else 5.0

    sigma_cx = float(np.clip(sigma_cx, 0.02, 5.0))
    sigma_cy = float(np.clip(sigma_cy, 0.02, 5.0))
    return sigma_cx, sigma_cy


# ---------------------------------------------------------------------------
# Top-level API
# ---------------------------------------------------------------------------

def find_centre(
    image: np.ndarray,
    cx_seed: Optional[float] = None,
    cy_seed: Optional[float] = None,
    var_r_min_px: float = 5.0,
    var_r_max_px: Optional[float] = None,
    var_n_bins: int = 250,
    var_search_px: float = 15.0,
) -> CentreResult:
    """
    Run the two-pass azimuthal variance centre finder and return a CentreResult.

    Parameters
    ----------
    image        : 2-D uint16 or float ndarray — ROI containing the fringe pattern
    cx_seed      : initial x guess (pixels); defaults to image centre
    cy_seed      : initial y guess (pixels); defaults to image centre
    var_r_min_px : inner exclusion radius for variance computation (pixels)
    var_r_max_px : outer radius; defaults to min(H,W)//2 - 10
    var_n_bins   : number of r² bins used in variance cost
    var_search_px: half-width of coarse grid search (pixels)
    """
    H, W = image.shape
    if cx_seed is None:
        cx_seed = (W - 1) / 2.0
    if cy_seed is None:
        cy_seed = (H - 1) / 2.0

    # Clip extreme outliers so hot pixels don't bias the variance minimum
    p99_5 = float(np.percentile(image, 99.5))
    image_for_cost = np.clip(image, None, p99_5)

    if var_r_max_px is None:
        var_r_max_px = float(min(H, W) // 2 - 10)

    cx_fine, cy_fine, cost_min, grid_cx, grid_cy, grid_cost = azimuthal_variance_centre(
        image_for_cost, cx_seed, cy_seed,
        var_r_min_px=var_r_min_px,
        var_r_max_px=var_r_max_px,
        var_n_bins=var_n_bins,
        var_search_px=var_search_px,
    )

    r_min_sq = var_r_min_px ** 2
    r_max_sq = var_r_max_px ** 2

    def _cost_fn(xy):
        return _variance_cost(xy[0], xy[1], image_for_cost, r_min_sq, r_max_sq, var_n_bins)

    sigma_cx, sigma_cy = estimate_centre_uncertainty(cx_fine, cy_fine, _cost_fn)

    return CentreResult(
        cx           = cx_fine,
        cy           = cy_fine,
        sigma_cx     = sigma_cx,
        sigma_cy     = sigma_cy,
        two_sigma_cx = 2.0 * sigma_cx,
        two_sigma_cy = 2.0 * sigma_cy,
        cost_at_min  = cost_min,
        grid_cx      = grid_cx,
        grid_cy      = grid_cy,
        grid_cost    = grid_cost,
    )


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    """
    Load a user-selected .npy ROI, run two-pass azimuthal variance centre
    finding, and display:
      - Left  : image with located centre overlaid
      - Middle: 1-D variance curve along cx (cy fixed at minimum)
      - Right : 1-D variance curve along cy (cx fixed at minimum)
    """
    root = tk.Tk()
    root.withdraw()
    npy_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                           r"..\raw_images_with_metadata")
    npy_file = filedialog.askopenfilename(
        title="Select L1.1 numpy array (.npy)",
        initialdir=os.path.normpath(npy_dir),
        filetypes=[("NumPy array", "*.npy"), ("All files", "*.*")],
    )
    root.destroy()
    if not npy_file:
        print("No file selected — exiting.")
        return

    src   = pathlib.Path(npy_file)
    image = np.load(src)
    print(f"File  : {src.name}")
    print(f"Shape : {image.shape}  dtype: {image.dtype}")
    print(f"Range : {image.min()} – {image.max()}  ADU")

    if image.ndim != 2:
        raise ValueError(f"Expected a 2-D array, got shape {image.shape}")

    print("\nRunning two-pass azimuthal variance centre finding …")
    cr = find_centre(image)

    print(f"\nCentre  : cx = {cr.cx:.3f} px,  cy = {cr.cy:.3f} px")
    print(f"  σ_cx  = {cr.sigma_cx:.3f} px  (2σ = {cr.two_sigma_cx:.3f} px)")
    print(f"  σ_cy  = {cr.sigma_cy:.3f} px  (2σ = {cr.two_sigma_cy:.3f} px)")
    print(f"  cost at min : {cr.cost_at_min:.4g}")

    # ── Save centre result ────────────────────────────────────────────────────
    centre_path = src.with_name(src.stem.replace("_L1.1", "") + "_centre.npz")
    np.savez(
        centre_path,
        cx       = np.array(cr.cx),
        cy       = np.array(cr.cy),
        sigma_cx = np.array(cr.sigma_cx),
        sigma_cy = np.array(cr.sigma_cy),
    )
    print(f"Centre saved  : {centre_path}")

    # ── Shared variance parameters ────────────────────────────────────────────
    H, W         = image.shape
    var_r_max_px = float(min(H, W) // 2 - 10)
    r_min_sq     = 5.0 ** 2
    r_max_sq     = var_r_max_px ** 2
    n_var_bins   = 250
    var_search_px = 15.0
    grid_step     = max(2.0, var_search_px / 8.0)

    p99_5 = float(np.percentile(image, 99.5))
    img_c = np.clip(image, None, p99_5)

    # Coarse grid 1-D slices (row 1) — evaluated at the grid_step spacing,
    # cy fixed at grid_cy for cx panel and vice-versa.
    # These are the actual points the grid search evaluated along each axis.
    cx_seed = (W - 1) / 2.0
    cy_seed = (H - 1) / 2.0
    grid_offsets = np.arange(-var_search_px, var_search_px + grid_step * 0.5, grid_step)
    grid_cx_pts  = cx_seed + grid_offsets
    grid_cy_pts  = cy_seed + grid_offsets
    grid_cost_cx = np.array([
        _variance_cost(cx, cr.grid_cy, img_c, r_min_sq, r_max_sq, n_var_bins)
        for cx in grid_cx_pts
    ])
    grid_cost_cy = np.array([
        _variance_cost(cr.grid_cx, cy, img_c, r_min_sq, r_max_sq, n_var_bins)
        for cy in grid_cy_pts
    ])
    # Smooth background line for the coarse panels (same range, many points)
    coarse_cx_line = np.linspace(grid_cx_pts[0], grid_cx_pts[-1], 300)
    coarse_cy_line = np.linspace(grid_cy_pts[0], grid_cy_pts[-1], 300)
    coarse_cost_cx_line = np.array([
        _variance_cost(cx, cr.grid_cy, img_c, r_min_sq, r_max_sq, n_var_bins)
        for cx in coarse_cx_line
    ])
    coarse_cost_cy_line = np.array([
        _variance_cost(cr.grid_cx, cy, img_c, r_min_sq, r_max_sq, n_var_bins)
        for cy in coarse_cy_line
    ])

    # Fine NM scan (row 2) — narrow window around Nelder-Mead result
    fine_half = 5.0
    fine_pts  = 201
    fine_cx_scan = np.linspace(cr.cx - fine_half, cr.cx + fine_half, fine_pts)
    fine_cy_scan = np.linspace(cr.cy - fine_half, cr.cy + fine_half, fine_pts)
    fine_cost_cx = np.array([
        _variance_cost(cx, cr.cy, img_c, r_min_sq, r_max_sq, n_var_bins)
        for cx in fine_cx_scan
    ])
    fine_cost_cy = np.array([
        _variance_cost(cr.cx, cy, img_c, r_min_sq, r_max_sq, n_var_bins)
        for cy in fine_cy_scan
    ])

    # ── Plotting — 2 rows × 3 cols ────────────────────────────────────────────
    fig = plt.figure(figsize=(17, 10))
    gs  = fig.add_gridspec(2, 3, hspace=0.42, wspace=0.32)

    vlo = float(np.percentile(image, 1))
    vhi = float(np.percentile(image, 99))

    # ── Row 0: coarse grid search results ────────────────────────────────────

    # [0,0] Image — grid best marked
    ax00 = fig.add_subplot(gs[0, 0])
    ax00.imshow(image, cmap="gray", origin="lower", vmin=vlo, vmax=vhi, aspect="equal")
    ax00.axhline(cr.grid_cy, color="lime",  linewidth=0.8, linestyle="--", alpha=0.9)
    ax00.axvline(cr.grid_cx, color="lime",  linewidth=0.8, linestyle="--", alpha=0.9)
    ax00.plot(cr.grid_cx, cr.grid_cy, "s", color="lime",
              markersize=10, markeredgewidth=1.5, markerfacecolor="none",
              label=f"Grid best")
    ax00.set_title(f"Pass 1 — coarse grid  (step = {grid_step:.0f} px)\n"
                   f"cx = {cr.grid_cx:.2f} px,  cy = {cr.grid_cy:.2f} px",
                   fontsize=9)
    ax00.set_xlabel("Column (pixel)", fontsize=8)
    ax00.set_ylabel("Row (pixel)",    fontsize=8)
    ax00.tick_params(labelsize=7)

    # [0,1] Variance vs cx — coarse, with actual grid points as markers
    ax01 = fig.add_subplot(gs[0, 1])
    ax01.plot(coarse_cx_line, coarse_cost_cx_line,
              color="steelblue", linewidth=1.0, alpha=0.5, zorder=1)
    ax01.plot(grid_cx_pts, grid_cost_cx,
              "o", color="steelblue", markersize=10, markeredgewidth=0.8,
              markeredgecolor="navy", zorder=2, label=f"{len(grid_cx_pts)} grid points")
    ax01.axvline(cr.grid_cx, color="lime", linewidth=1.2,
                 label=f"grid best cx = {cr.grid_cx:.2f} px")
    ax01.set_title("Variance vs cx  [grid search, cy fixed at seed]", fontsize=9)
    ax01.set_xlabel("cx  (pixel)", fontsize=8)
    ax01.set_ylabel("Azimuthal variance cost", fontsize=8)
    ax01.tick_params(labelsize=7)
    ax01.legend(fontsize=7, loc="upper right")

    # [0,2] Variance vs cy — coarse, with actual grid points as markers
    ax02 = fig.add_subplot(gs[0, 2])
    ax02.plot(coarse_cy_line, coarse_cost_cy_line,
              color="darkorange", linewidth=1.0, alpha=0.5, zorder=1)
    ax02.plot(grid_cy_pts, grid_cost_cy,
              "o", color="darkorange", markersize=10, markeredgewidth=0.8,
              markeredgecolor="saddlebrown", zorder=2, label=f"{len(grid_cy_pts)} grid points")
    ax02.axvline(cr.grid_cy, color="lime", linewidth=1.2,
                 label=f"grid best cy = {cr.grid_cy:.2f} px")
    ax02.set_title("Variance vs cy  [grid search, cx fixed at seed]", fontsize=9)
    ax02.set_xlabel("cy  (pixel)", fontsize=8)
    ax02.set_ylabel("Azimuthal variance cost", fontsize=8)
    ax02.tick_params(labelsize=7)
    ax02.legend(fontsize=7, loc="upper right")

    # ── Row 1: Nelder-Mead refined results ───────────────────────────────────

    # [1,0] Image — NM result marked
    ax10 = fig.add_subplot(gs[1, 0])
    ax10.imshow(image, cmap="gray", origin="lower", vmin=vlo, vmax=vhi, aspect="equal")
    ax10.axhline(cr.cy, color="cyan",   linewidth=0.8, linestyle="--", alpha=0.9)
    ax10.axvline(cr.cx, color="cyan",   linewidth=0.8, linestyle="--", alpha=0.9)
    ax10.plot(cr.cx, cr.cy, "+", color="yellow", markersize=14, markeredgewidth=1.5)
    ax10.set_title(f"Pass 2 — Nelder-Mead refinement\n"
                   f"cx = {cr.cx:.3f} ± {cr.sigma_cx:.3f} px\n"
                   f"cy = {cr.cy:.3f} ± {cr.sigma_cy:.3f} px",
                   fontsize=9)
    ax10.set_xlabel("Column (pixel)", fontsize=8)
    ax10.set_ylabel("Row (pixel)",    fontsize=8)
    ax10.tick_params(labelsize=7)

    # [1,1] Variance vs cx — fine scan around NM result
    ax11 = fig.add_subplot(gs[1, 1])
    ax11.plot(fine_cx_scan, fine_cost_cx, color="steelblue", linewidth=1.2,
              marker="o", markersize=4, markerfacecolor="steelblue",
              markeredgewidth=0)
    ax11.axvline(cr.cx, color="red", linewidth=1.2,
                 label=f"NM cx = {cr.cx:.3f} px")
    ax11.axvspan(cr.cx - cr.sigma_cx,     cr.cx + cr.sigma_cx,
                 alpha=0.22, color="red",    label=f"±1σ = {cr.sigma_cx:.3f} px")
    ax11.axvspan(cr.cx - cr.two_sigma_cx, cr.cx + cr.two_sigma_cx,
                 alpha=0.10, color="orange", label=f"±2σ = {cr.two_sigma_cx:.3f} px")
    ax11.set_title(f"Variance vs cx  [Nelder-Mead, ±{fine_half:.0f} px window]", fontsize=9)
    ax11.set_xlabel("cx  (pixel)", fontsize=8)
    ax11.set_ylabel("Azimuthal variance cost", fontsize=8)
    ax11.tick_params(labelsize=7)
    ax11.legend(fontsize=7, loc="upper right")

    # [1,2] Variance vs cy — fine scan around NM result
    ax12 = fig.add_subplot(gs[1, 2])
    ax12.plot(fine_cy_scan, fine_cost_cy, color="darkorange", linewidth=1.2,
              marker="o", markersize=4, markerfacecolor="darkorange",
              markeredgewidth=0)
    ax12.axvline(cr.cy, color="red", linewidth=1.2,
                 label=f"NM cy = {cr.cy:.3f} px")
    ax12.axvspan(cr.cy - cr.sigma_cy,     cr.cy + cr.sigma_cy,
                 alpha=0.22, color="red",    label=f"±1σ = {cr.sigma_cy:.3f} px")
    ax12.axvspan(cr.cy - cr.two_sigma_cy, cr.cy + cr.two_sigma_cy,
                 alpha=0.10, color="orange", label=f"±2σ = {cr.two_sigma_cy:.3f} px")
    ax12.set_title(f"Variance vs cy  [Nelder-Mead, ±{fine_half:.0f} px window]", fontsize=9)
    ax12.set_xlabel("cy  (pixel)", fontsize=8)
    ax12.set_ylabel("Azimuthal variance cost", fontsize=8)
    ax12.tick_params(labelsize=7)
    ax12.legend(fontsize=7, loc="upper right")

    fig.suptitle(
        f"Two-pass azimuthal variance centre finder — {src.name}  |  "
        f"grid cost = {cr.grid_cost:.4g}  →  NM cost = {cr.cost_at_min:.4g}",
        fontsize=11, fontweight="bold",
    )
    fig.tight_layout()
    plt.show()


if __name__ == "__main__":
    main()
